### ISSUE TITLE
Some mistake in clac_crc() comment. 

### ISSUE THREAD

**Issue by ganioc** [tehmaze/xmodem#23]
I used the algorithm in the code, it works good. But the comment of calc_crc() function puzzled me  a lot.

'''
Calculate the Cyclic Redundancy Check for a given block of data, can
also be used to update a CRC.
 crc = modem.calc_crc('hello')
 crc = modem.calc_crc('world', crc)
hex(crc)
'0xd5e3'
'''

Should the hex(crc) be 0x4ab3 instead of 0xd5e3? I checked many times. The algorithm is right. But the example  result listed above is far different from whatever I could get.

**Comment by jquast** [comment]
sounds like docstring bug, thank you @ganioc
