### ISSUE TITLE
Zmodem suggest

### ISSUE THREAD

**Issue by qhsong** [tehmaze/xmodem#30]
Hi,
I find you are trying to understand the Zmodem protocol and port it into python.
But why not we  use `subprocess.popen()` to call `rz` and `sz` to recv and send file?

I just use it to send an file by zmodem and also have good performance.

Is it a good idea? If so, maybe I can send an PR for it.

**Comment by tehmaze** [comment]
What's the point of wrapping a subprocess.popen in a package? If you want to fork out to rz/sz in your project, then just do so.

**Comment by berlinsaint** [comment]
@qhsong  哥们 ，可以贴一下 你使用 subprocess 处理 rzsz 连接的代码么，最近我也在考虑这种方式，但是我使用总会卡，希望学习下你的代码
