### ISSUE TITLE
Problems with pypi page

### ISSUE THREAD

**Issue by larsks** [tehmaze/xmodem#31]
I noticed that [the PyPi page](https://pypi.python.org/pypi/modem/1.0) shows:

```
YMODEM: | © 1985 Chunk Forsberg, Omen Technology Inc.
ZMODEM: | © 1986 Chunk Forsberg, Omen Technology Inc.
```

Pretty sure his name was *Chuck* Forsberg, unless he had an alternate career as a Chippendale of which I was previously unaware.

**Comment by tehmaze** [comment]
Wrong project.
