### ISSUE TITLE
Missing LICENSE file when downloading from pypi

### ISSUE THREAD

**Issue by mniestroj** [tehmaze/xmodem#41]
There is no LICENSE file included when downloading from pypi: https://files.pythonhosted.org/packages/29/5d/a20d7957f207fc4c4c143881ca7b9617ab7700c153012372ef0a934c7710/xmodem-0.4.6.tar.gz

Hence it makes it difficult to attach license file automatically in projects such as Buildroot: https://patchwork.ozlabs.org/project/buildroot/patch/20200430132020.2476465-1-m.niestroj@grinn-global.com/

**Comment by tehmaze** [comment]
Fixed in #42, thanks!
