### ISSUE TITLE
In recv, if char is something unexpected, it will loop until error_count > retry without re-evaluating char

### ISSUE THREAD

**Issue by g-frenette** [tehmaze/xmodem#44]
In [xmodem/__init__.py](https://github.com/tehmaze/xmodem/blob/master/xmodem/__init__.py), between lines 472 and 510, we have a while loop and `if` clauses to determine the appropriate action to take. I had a case where I would have the variable `char` being something unexpected and then the execution would go in the `else` statement. However, `char` is never re-evaluated in that `else`. It would then just loop for retries in the `else`. I believe that adding this statement: `char = self.getc(1, timeout)` after line 504 would solve this undesirable behavior.

Thanks for your time!

**Comment by jquast** [comment]
I believe this is fixed in next release by c99d3e73c5c703f63c5a80ac310238fd8aa3766f, thanks for the report!
